//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVolunteer.Models.SQL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumSD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlbumSD()
        {
            this.PostSDs = new HashSet<PostSD>();
        }
    
        public string AlbumID { get; set; }
        public bool Permission { get; set; }
    
        public virtual GroupSD GroupSD { get; set; }
        public virtual ProjectSD ProjectSD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostSD> PostSDs { get; set; }
    }
}
