//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVolunteer.Models.SQL.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iVolunteerEntities : DbContext
    {
        public iVolunteerEntities()
            : base("name=iVolunteerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AlbumSD> AlbumSDs { get; set; }
        public virtual DbSet<GroupSD> GroupSDs { get; set; }
        public virtual DbSet<PostSD> PostSDs { get; set; }
        public virtual DbSet<ProjectSD> ProjectSDs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User_Group> User_Group { get; set; }
        public virtual DbSet<User_Project> User_Project { get; set; }
    }
}
