//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVolunteer.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQL_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SQL_Account()
        {
            this.SQL_Message = new HashSet<SQL_Message>();
            this.SQL_User_Friend = new HashSet<SQL_User_Friend>();
            this.SQL_User_Friend1 = new HashSet<SQL_User_Friend>();
            this.SQL_User_Group = new HashSet<SQL_User_Group>();
            this.SQL_User_Project = new HashSet<SQL_User_Project>();
        }
    
        public string UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string IndentifyID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> DateOfChange { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActivate { get; set; }
        public bool IsConfirm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_Message> SQL_Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_User_Friend> SQL_User_Friend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_User_Friend> SQL_User_Friend1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_User_Group> SQL_User_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_User_Project> SQL_User_Project { get; set; }
    }
}
