//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVolunteer.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQL_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SQL_Account()
        {
            this.SQL_AcAl_Relation = new HashSet<SQL_AcAl_Relation>();
            this.SQL_Message = new HashSet<SQL_Message>();
            this.SQL_AcIm_Relation = new HashSet<SQL_AcIm_Relation>();
            this.SQL_AcPo_Relation = new HashSet<SQL_AcPo_Relation>();
            this.SQL_Friendship = new HashSet<SQL_Friendship>();
            this.SQL_Friendship1 = new HashSet<SQL_Friendship>();
            this.SQL_AcGr_Relation = new HashSet<SQL_AcGr_Relation>();
            this.SQL_AcPr_Relation = new HashSet<SQL_AcPr_Relation>();
        }
    
        public string UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string IndentifyID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> DateOfChange { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActivate { get; set; }
        public bool IsConfirm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_AcAl_Relation> SQL_AcAl_Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_Message> SQL_Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_AcIm_Relation> SQL_AcIm_Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_AcPo_Relation> SQL_AcPo_Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_Friendship> SQL_Friendship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_Friendship> SQL_Friendship1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_AcGr_Relation> SQL_AcGr_Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_AcPr_Relation> SQL_AcPr_Relation { get; set; }
    }
}
