//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVolunteer.Models.Data_Definition_Class.SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iVolunteerEntities : DbContext
    {
        public iVolunteerEntities()
            : base("name=iVolunteerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SQL_Account> SQL_Account { get; set; }
        public virtual DbSet<SQL_Album> SQL_Album { get; set; }
        public virtual DbSet<SQL_Group> SQL_Group { get; set; }
        public virtual DbSet<SQL_Message> SQL_Message { get; set; }
        public virtual DbSet<SQL_Plan> SQL_Plan { get; set; }
        public virtual DbSet<SQL_Post> SQL_Post { get; set; }
        public virtual DbSet<SQL_Project> SQL_Project { get; set; }
        public virtual DbSet<SQL_User_Friend> SQL_User_Friend { get; set; }
        public virtual DbSet<SQL_User_Group> SQL_User_Group { get; set; }
        public virtual DbSet<SQL_User_Project> SQL_User_Project { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
