//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVolunteer.Models.Data_Definition_Class.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQL_Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SQL_Album()
        {
            this.SQL_Post = new HashSet<SQL_Post>();
        }
    
        public string AlbumID { get; set; }
        public string ProjectID { get; set; }
        public string GroupID { get; set; }
        public bool Permission { get; set; }
    
        public virtual SQL_Group SQL_Group { get; set; }
        public virtual SQL_Project SQL_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_Post> SQL_Post { get; set; }
    }
}
